[package]
name = "rust-2048-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.127.0"
piston2d-opengl_graphics = "0.82.0"